export VERSION="\"2.13.16\""
export REGISTRY_ADDRESS="\"harbor.runai.local\""
export USERNAME="\"admin\""
export PASSWORD="\"kirson\""
export KUBECONFIG_PATH="\"$HOMEkirson/runai.local/inventory/runai.local/artifacts/admin.conf\""
export ROOTCA="\"$HOMEkirson/runai.local/air-gapped/cert/rootCA.pem\""
export CLUSTER_NAME="\"runai\""
export CHARTURL="\"https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts\""
export DOMAIN="haproxy.runai.local"
export FRONT-CLIENT_ID="\"runai\""
export FRONT-USERNAME="\"test@run.ai\""
export FRONT-PASSWORD="\"Abcd!234\""
export CLUSTER_NAME="\"runai\""

