---
- name: rakuten-ca-copy
  hosts: all
  become: true
  tasks:
    - name: rakuten.crt
      ansible.builtin.copy:
        src: rakuten-client.crt
        dest: /usr/local/share/ca-certificates/rakuten-client.crt
        owner: root
        mode: '0600'

    - name: restart-ca
      shell: /usr/sbin/update-ca-certificates --fresh


    - name: restart kubelet
      ansible.builtin.systemd:
        state: restarted
        name: kubelet

    - name: restart containerd
      ansible.builtin.systemd:
        state: restarted
        name: containerd
