---
- name: Create Kubernetes Secret
  hosts: localhost
  gather_facts: no
  vars_files:
  - runai_vars.yaml
  tasks:
    - name: Ensure TLS Secret exists
      k8s:
        namespace: runai-backend
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: runai-backend-tls
          type: kubernetes.io/tls
          data:
            tls.crt: "{{ lookup('file', crt) | b64encode }}"
            tls.key: "{{ lookup('file', key) | b64encode }}"

