---
- name: Setup Kubernetes Resources
  hosts: localhost
  gather_facts: true
  vars_files:
    - runai_vars.yaml
  tasks:
    - name: Create Namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: runai-backend

