---
- name: Generate Variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get domain
      shell: |
        echo $(kubectl get route -A | grep oauth | awk '{print $3}' | sed 's/^[^.]*\.//')
      register: domain_output
      changed_when: true


    - name: Get node
      shell: |
        echo $(kubectl get node |  grep -vi name | awk '{print $1}')
      register: node_output
      changed_when: false


    - name: Save var
      lineinfile:
        path: "{{ playbook_dir }}/runai_vars.yaml"
        line: "node: {{ node_output.stdout }}"
        create: yes
