version: '3'

services:
  bind9:
    container_name: dns-prod-1
    image: ubuntu/bind9
    ports:
      - "53:53"
      - "53:53/udp"
    environment:
      - BIND9_USER=root
      - TZ=Asia/Jerusalem
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped
