---
- name: Create ConfigMap from file
  hosts: localhost
  gather_facts: false
  vars_files:
    - runai_vars.yaml
  become: no
  tasks:
    - name: Create ConfigMap
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: runai-patch
            namespace: runai-backend
          data:
            rootCA.pem: |
              {{ lookup('file', rootCA) }}

    - name: Create ConfigMap
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: runai-patch
            namespace: runai
          data:
            rootCA.pem: |
              {{ lookup('file', rootCA) }}

