apiVersion: run.ai/v2alpha1
kind: TrainingWorkload 
metadata:
  name: riva-api-inference
  namespace: runai-phd
  labels:
    app: riva-api
    chart: riva-api-2.7.0
    release: release-name
    heritage: Helm
spec:
      schedulerName: runai-scheduler
      containers:
        - name: riva-speech-api
          image: nvcr.io/nvidia/riva/riva-speech:2.7.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nvidia.com/gpu: 1
          command: ["/opt/riva/bin/start-riva"]
          args:
            - "--asr_service=true"
            - "--nlp_service=true"
            - "--tts_service=true"
          env:
            - name: TRTIS_MODEL_STORE
              value: "/data/models"
            - name: LD_PRELOAD
              value: ""
          ports:
            - containerPort: 50051
              name: speech-grpc
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: grpc
            - containerPort: 8002
              name: metrics
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 10
          startupProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
            initialDelaySeconds: 10
            failureThreshold: 12
            periodSeconds: 10
          volumeMounts:
            - mountPath: /data/
              name: workdir

      initContainers:
        - name: riva-model-init
          image: nvcr.io/nvidia/riva/riva-speech:2.7.0-servicemaker
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: artifact-volume
              mountPath: /rmir
            - name: workdir
              mountPath: /data/
          command:
            - download_and_deploy_ngc_models
            - "nvidia/riva/rmir_asr_conformer_en_us_str:2.7.0"
            - "nvidia/riva/rmir_asr_conformer_en_us_ofl:2.7.0"
            - "nvidia/riva/rmir_nlp_intent_slot_bert_base:2.7.0"
            - "nvidia/riva/rmir_nlp_question_answering_bert_base:2.7.0"
            - "nvidia/riva/rmir_nlp_punctuation_bert_base_en_us:2.7.0"
            - "nvidia/riva/rmir_nlp_text_classification_bert_base:2.7.0"
            - "nvidia/riva/rmir_nlp_named_entity_recognition_bert_base:2.7.0"
            - "nvidia/riva/rmir_tts_fastpitch_hifigan_en_us:2.7.0"
          env:
            - name: NGC_CLI_ORG
              value: "nvidia"
            - name: NGC_CLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: modelpullsecret
                  key: apikey
            - name: MODEL_DEPLOY_KEY
              valueFrom:
                secretKeyRef:
                  name: riva-model-deploy-key
                  key: key
      volumes:
        - name: artifact-volume
          hostPath:
            path: /data/riva/
            type: DirectoryOrCreate
        - name: workdir
          hostPath:
            path: /data/riva
            type: DirectoryOrCreate
