---
- name: Update resolved.conf and restart systemd-resolved
  hosts: your_target_hosts  # Update with your target hosts
  become: yes  # Use sudo to execute the commands
  tasks:
    - name: Update DNSStubListener in resolved.conf
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNSStubListener='
        line: 'DNSStubListener=no'

    - name: Restart systemd-resolved service
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted

---
- name: Deploy Docker service using docker-compose
  hosts: your_target_hosts  # Update with your target hosts
  become: yes  # Use sudo to execute the commands

  tasks:
    - name: Ensure docker and docker-compose are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker-compose

    - name: Deploy service using docker-compose
      ansible.builtin.docker_compose:
        project_src: /path/to/your/docker-compose/directory  # Update with the path to your docker-compose file directory
        state: present


---
- name: Configure BIND DNS server
  hosts: your_target_hosts  # please replace with your actual target hosts or group
  become: yes  # necessary for permissions to write the file
  gather_facts: no  # speeds up the playbook execution
  tasks:
    - name: Ensure BIND directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/bind

    - name: Set up named.conf
      ansible.builtin.copy:
        dest: /etc/bind/named.conf
        content: |
          acl internal {
             192.168.10.0/24;
             172.17.0.0/16;
             172.18.0.0/16;
          };

          options {
              forwarders {
                1.1.1.1;
                8.8.8.8;
              };
              allow-query { internal; };
          };

          zone "runai.local" IN {
              type master;
              file "/etc/bind/db.runai.local";
          };

    - name: Set up db.runai.local
      ansible.builtin.copy:
        dest: /etc/bind/db.runai.local
        content: |
          ;
          ; BIND data file for runai.local
          ;
          $TTL    2d
          $ORIGIN runai.local.
          @       IN      SOA     ns.runai.local. admin.runai.local. (
                                    4         ; Serial
                                   12h        ; Refresh
                                   15m        ; Retry
                                    3w        ; Expire
                                   2h )       ; Negative Cache TTL
          ;
          @       IN      NS      ns.runai.local.
          ns      IN      A       192.168.10.210
          ; Control-Plane

          master-0  IN     A       192.168.10.200
          master-1  IN     A       192.168.10.201
          master-2  IN     A       192.168.10.202

          ; Workers
          worker-0  IN     A       192.168.10.203
          worker-1  IN     A       192.168.10.204
          worker-2  IN     A       192.168.10.206

          ; Proxy
          haproxy   IN     A       192.168.10.205

